# Generated by Django 4.0 on 2021-12-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
