# Generated by Django 4.0 on 2021-12-23 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_shows_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='date_aired',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
