# Generated by Django 4.0 on 2021-12-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_shows_date_aired'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shows',
            new_name='Show',
        ),
    ]
